sudo: required

services:
  - docker

before_install:
  - docker build -t vasianurag/newink-dev -f dockerfile.dev .

script:
  - docker run vasianurag/newink-dev npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: "$AWS_ACCESS_KEY_ELASTICBEANSTALK"
  secret_access_key:
    secure: "$AWS_SECRET_ACCESS_KEY_ELASTICBEANSTALK"
  region: "ap-south-1"
  app: "newink-website"
  env: "newink-websote-env"
  bucket_name: "elasticbeanstalk-ap-south-1-690896776770"
  on:
    branch: master
